name: ci

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dev dependencies
        run: pip install -r dev-requirements.txt
      - name: Run linter
        run: ruff check
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build micropython
        run: |
          git clone --depth 1 https://github.com/micropython/micropython.git
          cd micropython
          git submodule update --init
          make -C mpy-cross
          cp mpy-cross/build/mpy-cross /usr/local/bin/
          make -C ports/unix
          cp ports/unix/build-standard/micropython /usr/local/bin/
          cd ..
          rm -rf micropython
      - name: Install test dependencies
        run: ./bin/setup
      - name: Install the package dependencies
        run: "micropython -m mip install github:${{ github.repository }}@${{ github.ref_name }}"
      - name: Run unit tests
        run: micropython -m unittest
        env:
          MICROPYPATH: "${{ github.workspace }}:.frozen:~/.micropython/lib:/usr/lib/micropython:${{ github.workspace }}/tests/mocks"
      - name: Install mosquitto
        run: |
          sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
          sudo apt-get update
          sudo apt-get install -y mosquitto
      - name: Generate test certificate for MQTTS
        run: ./bin/generate_cert
      - name: Set password for device
        run: |
          mosquitto_passwd -c -b mosquitto_passwords device my_password
          chmod 700 mosquitto_passwords
      - name: Run end-to-end tests
        run: ./bin/test_e2e
